### ISSUE TITLE
problem with problem hashes

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#100]
I seem to have got my version into a funny state and the hashes are causing problems in make:

  File "/home/pjr/research/MyPyTutor3/MyPyTutor/code/hashes.py", line 211, in update_hashes
    '''
AssertionError: Tutorial hash  collision!
Note that reverting to a previous version of a tutorial is not supported.

If you have not pushed your changes to the server, replace the local
tutorial_hash_mappings file with a fresh copy from the server, and remake.

If you have pushed your changes to the server, you will need to make some
change to the local file so as to alter its hash.

make: [tutorials] Error 1 (ignored)

Neither of the above suggestions seem to work

**Comment by sapi** [comment]
Should be resolved if you use `make push`.
