### ISSUE TITLE
Show Submissions gives Online Service Error box

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#101]
I am logged in to MPT and try to do a Show Submissions and get the Online Service Error box.
It's the first time I have tried from home so I am not sure if that's the problem

**Comment by sapi** [comment]
We've somehow let the hashes get out of sync (which can happen in development, but which we should be able to avoid in production, given how few updates to the tutorials we'll be using).

I've removed the offending hash, so if it was just one submission, you should no longer get the issue.

If it was more than one, you can get MPT to ignore the problem by removing everything at `/opt/local/share/MyPyTutor/MPT3_CSSE1001/data/submissions/uqprobin` (which will clear your submissions).

(Side note: this is intentionally a server error, as it should never occur.)

**Comment by pjritee** [comment]
I had to remove all the submissions. When I do a Show Submissions the "While Using Break" comes up as Unknown (but that's the only one)
