### ISSUE TITLE
getting started with MPT

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#104]
The MPT help will now be a web page - but we also need a HOWTO to help students to get it installed.
This was discussed on the web page site: 25.
I am not sure where the best place for this.
Also the mpt_installer code probably needs updating.

**Comment by starsnabove** [comment]
When I can be assured that everything works I was going to do a video of how to. But I guess a text version will still be good. I think we talked about that being the opening screen.



—

**Comment by pjritee** [comment]
Yes - you will need to wait until things have settled down otherwise it would be a waste of time.
Do you mean the opening screen of MPT? That requires MPT to be installed already.
Maybe you mean the MPT help - but that's a web page - maybe the opening screen could suggest going to the help menu????

**Comment by starsnabove** [comment]
Sorry didn't see the word install.  If the install procedure is complete then we can edit the existing web page for that.



—

**Comment by sapi** [comment]
The updates to the MPT installer were so minor that the existing webpage should do fine.

Probably the only thing we need to do is change it so that it it refers to Python 3, not Python 2.
