### ISSUE TITLE
admin interface

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#105]
The old system had an admin interface to do various tasks. Many of them are not needed anymore.
It also shared the server code with the student interface code which was probably not a great idea.
In any case, in the short term I need to be able to do:

- [x] Unset late flag
- [x] View student results
- [x] Download marks

In more detail:

1. Unset the late flag for a given student for a collection of problems.
2. Look to see the %age of the problems students have completed (I like to send a congrats message to students who get them all done by early week 1.

Longer term (before the end of semester):
Be able to download the marks to merge in with my overall marks file.

**Comment by jgat** [comment]
This is partially encapsulated in #46 (and possibly #45).
Point 1 (unsetting the late flag) is half-done: see #90.

**Comment by jgat** [comment]
(I'm tempted to consider a web-based admin interface, which I might sketch out this weekend)

**Comment by pjritee** [comment]
A web-based interface makes good sense. Will I be the only one using it? I don't mind - does it make sense to allow tutors to unset late flags?

**Comment by jgat** [comment]
From the technical angle, it'll be super-easy to say who has permissions to the admin interface by having a hardcoded list of admin users (e.g. `['uqprobin']`) - later versions could probably introduce varying levels of permission (e.g. can see student progress, but not edit anything).

From an administration angle, doing the "unset late flag" is essentially granting an indefinite extension to an assessment item - normally, that's the course coordinator's job, but if you want to give that power to tutors as well, it's your call.

**Comment by sapi** [comment]
I think it would probably be better to leave it to just Peter, so that
tutors aren't inundated with requests for extensions. As Jackson says, it's
a bit above our pay grade.

**Comment by pjritee** [comment]
Fair enough - I am happy to do it all (I have been in the past)

**Comment by sapi** [comment]
I added a script for getting the student's marks.

It's trivial to get the percentage completion from that, either in Python or Excel (just count the number of columns which are OK).
