### ISSUE TITLE
Tests, Analysis and Hints disappear when an error occurs in the students code.

### ISSUE THREAD

**Issue by hendo-michael** [CSSE1001/MyPyTutor#114]

**Comment by hendo-michael** [comment]
![bug](https://cloud.githubusercontent.com/assets/5109410/6313790/028c5e96-ba09-11e4-81fe-d622c00251a6.PNG)

**Comment by sapi** [comment]
Can you please provide the code which caused that?

**Comment by hendo-michael** [comment]
Just any code that would fail when ran in IDLE. I used -> print 'test'

**Comment by sapi** [comment]
Thanks.  This is actually working as designed (as we can't run the tests on code which causes an error), but it does appear to be quite confusing.

I'll add a mock test with an error.
