### ISSUE TITLE
Keyring Saves Invalid Credentials

### ISSUE THREAD

**Issue by athleticus** [CSSE1001/MyPyTutor#128]
When running `code/MyPyTutor.py` and using keyring to save credentials, it will save them even if they do not authenticate successfully. Perhaps a better approach would be to authenticate first, or even to allow the user to update their credentials from the main GUI (i.e. what if a student changes their password?).

**Comment by sapi** [comment]
Cheers, I'll give it a look.

What I *thought* I was doing was attempting to authenticate as the very
last action before launching MPT, then clearing any failed credentials.
It's possible that I've forgotten to clear the username and / or password
correctly.

**Comment by sapi** [comment]
I switched to a more conservative clearing policy (it will now wipe credentials whenever anything goes wrong with a login).

It might be worth considering enabling updates from the main GUI.  At the moment, the main GUI doesn't touch the keyring at all.  That has the advantage of it not having to screw around with potentially unsuccessful imports, though.

Hopefully this behaviour means that users should never have a need to manually change passwords (as they are instead able to run MPT again, and use the resulting prompt).
