### ISSUE TITLE
Remove all tempfile download references

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#130]
On windows, downloading a zip file to `$TMP` will sporadically cause UAC to silently remove the file.  It's a 'feature'.

Any time that `.urlretrieve` is used without a `filename` parameter, it defaults to downloading in `$TMP`.  As a result, such downloads may fail on Windows.

Explicit filenames must therefore be given.  It might be nice to download to our own temp-ish location using randomised filnames (GUIDs, maybe?)

**Comment by sapi** [comment]
@pjritee indicated in #121 that this issue is also prevalent on Ubuntu.

I might just switch all operating systems to put tempfiles in `~/.mptrc` (via `mkstemp(..., dir='~/.mptrc/tmp)`) for more consistent performance.

**Comment by pjritee** [comment]
That seems like a good idea - this dir has to be created anyway so it may as well be used for tmp files
