### ISSUE TITLE
showing doc and viz don't work

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#135]
Both start up a new instance of the browser but use my home page - this used to work.

**Comment by sapi** [comment]
Cannot reproduce on OS X or Windows.

I suspect this might be an issue with your machine.

**Comment by pjritee** [comment]
But it used to work fine - I don't think my machine has changed in any way since then

**Comment by sapi** [comment]
Nothing should have changed on the code side either; I haven't touched that in ages.

Do you mind checking if `webbrowser` is working correctly from console?

````
In [1]: import webbrowser

In [2]: webbrowser.open('http://www.google.com')
Out[2]: True
````

**Comment by pjritee** [comment]
Was just trying as you sent this - it works as above (except I also get:
(process:7486): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

But I also get that if I do

firefox http://csse1001.uqcloud.net/mpt3/help

- that works as expected

**Comment by sapi** [comment]
Interesting.

I don't have a GUI version of Ubuntu to test this on at the moment, unfortunately (my VMs are all headless).

@starsnabove @RoryCharlton @athleticus Do any of you have a copy of Ubuntu you could test this on?

**Comment by pjritee** [comment]
Looks like a problem at my end - there was a system update this morning. I checked on my old laptop and your test above works - so it looks like maybe the system update has stuffed this up - same problem for both python2 and 3 so maybe a firefox update????

Just flipped my preferred browser to chromium and it works OK so there must have been a problem with a firefox update

**Comment by sapi** [comment]
Odd, but hopefully that means it won't impact too many students (few enough use Linux anyway).

**Comment by pjritee** [comment]
agreed
