### ISSUE TITLE
show submissions doesn't work

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#136]
It shows "Could not complete request" box.
Also, probably related, problems completed are not highlighted in blue

**Comment by sapi** [comment]
I can't reproduce this on OS X or Windows.

I did get a 'Could not complete request' once on startup, but when manually opting to show submissions, the popup appeared correctly.

(I'm going to look into the request failures more carefully this afternoon.)

**Comment by pjritee** [comment]
Also the status bar says Submitted: Unknown but if I do a "Submit Answer" it says it has already been submitted

**Comment by sapi** [comment]
Resolved: this was to do with changes to the tutorials (and therefore their hashes) in development.
