### ISSUE TITLE
Command-W on Mac causes MyPyTutor to quit when the script window is open

### ISSUE THREAD

**Issue by ShadovvMoon** [CSSE1001/MyPyTutor#139]
This makes me sad :cry:

**Comment by sapi** [comment]
This is working as designed (or, at least, as MyPyTutor has always worked).

I'm not sure what the original design reason for this was (as I just carried it over from the old version), but if I had to guess, I would suggest that it's to do with `idlelib`; we use an `EditorWindow` subclass from that module, but `idlelib` makes use of a ridiculous number of global variables and so might not like opening and closing.

At this point it's quite a pain to change, sorry.  (At the very least, you'd end up with a UI inconsistency, as the visible tests would no longer correspond to any code.)

**Comment by sapi** [comment]
Oh, and don't worry, it makes me sad too...but that's just Tk!

**Comment by ShadovvMoon** [comment]
D:

**Comment by sapi** [comment]
If it makes you feel any better, this is the same as any self-contained app
(eg, System Preferences).

**Comment by ShadovvMoon** [comment]
The main annoyance is that it's a separate window (so when I do command-w I just expect the script window to close). Also, when clicking 'Yes' to the save script dialog it closes the program

**Comment by sapi** [comment]
Yeah, that's all as designed (aka as it's always been).  If you close the
window (whether you save the script or not), the whole app will go down.

This is the *least* of the HIG violations on OS X, trust me... :P

**Comment by ShadovvMoon** [comment]
This is going to drive me insane xD
[Video linky](http://www.samuco.net/spartanx/video.mov)
