### ISSUE TITLE
Problems menu disappears when in script window

### ISSUE THREAD

**Issue by ShadovvMoon** [CSSE1001/MyPyTutor#140]

**Comment by sapi** [comment]
`idlelib` handles its own menu system, so it's unfortunately not possible to generate the problems menu dynamically (as the main window does).  (Well, it's possible, but you'd also have to regenerate all of the built-in menu items and bindings, using the special syntax that IDLE uses.)

Thankfully this is only a noticable problem on OS X (as under other operating systems, each window has its own menu, meaning that the problems menu is never 'hidden').
