### ISSUE TITLE
Add CSV support to admin interface

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#142]
We could streamline things by adding support for CSV upload and download to the admin interface.

Two things stand out:
- [x] Supporting mass upload of all enrolled students
- [ ] Allowing export of marks in CSV format for all enrolled students (see `/code/get_submissions.py`)

**Comment by jgat** [comment]
I've added a "CSV upload of all students" option.
@pjritee, if you could prepare a CSV file of students enrolled in the course, in the format `userid,name,email` (e.g. `s4237013,Jackson Gatenby,s4237013@student.uq.edu.au`), and then upload it to http://csse1001.uqcloud.net/cgi-bin/mpt3/admin.py, then this would help you to:
* ignore progress for people who are not enrolled (e.g. course tutors, students' private tutors, etc.)
* see progress for all students, including those who have never logged into MyPyTutor.

(Or, delegate the task of preparing that file to one of your tutors)

**Comment by pjritee** [comment]
The current class list looks like:
<tt>42370139,,  , Gatenby, Jackson   ,s4237013@student.uq.edu.au, DegreeCode, DegreeName</tt>

Would that do? I could pre-process the class list into your format easily enough but using the standard class list format might be easier for others.
What if I upload a class list and then the class list changes? Will the new list replace the old list?
WARNING there are a few students at UQ whose student number has one fewer digits.

**Comment by jgat** [comment]
I take it that format is common across UQ courses. I might just modify the
upload script to accept that format.

To solve the issue with one fewer digit, I might take the "sXXXX" bit from
the email instead of the student number (and explicitly terminate if it
doesn't look like XXX@student.uq.edu.au)

**Comment by pjritee** [comment]
Yes - it's the standard format for class lists we download. I use the sXXX from the email as well in my scripts for the same reason. Those extra slots after the student number are for grades and marks

**Comment by jgat** [comment]
I've made that change in 93ce50a.
Try uploading the course list at http://csse1001.uqcloud.net/cgi-bin/mpt3/admin.py and see if it works.

**Comment by pjritee** [comment]
Seems to work fine - thanks Jackson
