### ISSUE TITLE
Switch questions from compiler to ast

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#15]
There's a relatively quick way to migrate questions to `ast` that I figured might be handy for people.
1. Store a solution to the problem in a string var, ie `s = ...`
2. Parse this: 
   
   ```
   t = ast.parse(s)
   ```
3. Log all visits [using this](http://stackoverflow.com/questions/1515357/simple-example-of-how-to-use-ast-nodevisitor/1515403#1515403):
   
   ```
   class LoggingVisitor(ast.NodeVisitor):
       def generic_visit(self, node):
           print(type(node).__name__)
           super().generic_visit(node)
   ```
4. Visit the code:
   
   ```
   visitor = LoggingVisitor()
   visitor.visit(t)
   ```
5. Intercept calls of interest, eg:
   
   ```
   class CV(ast.NodeVisitor):
       def visit_arguments(self, node):
           import pdb; pdb.set_trace()
   ```
6. Visit the code again using this visitor:
   
   ```
   visitor = CV()
   visitor.visit(t)
   ```
7. From the console, examine things of interest, eg:
   
   ```
   (pdb) p node
   ...
   (pdb) p dir(node)
   ...
   (pdb) p dir(node.args)
   ...
   ```
8. Update `analysis.py`

**Comment by sapi** [comment]
**How to update tutorial questions**

What you need to do for each of the tutorials is covert the old code (single file, using `compiler`) to new code (.tut directory, using `ast`).

The best way to get a hang of how it all works is to look at some examples.  `class_use.tut` and `list3.tut` are both pretty good examples of what testing/analysis looks like.

A `.tut` package needs to have the following files:

* `description.html`
  * a description of the task, using the html that MPT 'knows about'
  * base it on the old description, but you might as well fix up any known issues as you go (eg, hard to understand questions)
* `config.py`
  * defines `SHORT_DESCRIPTION` to be a one-line explanation of the task
  * if the student is *not* writing a function, define `WRAP_STUDENT_CODE = True` (so that any `input` calls at global scope don't hang)
  * optionally, define `HINTS` as a list of strings
* `preload.py`
  * the initial code that should be loaded in the editor (will be in the existing .tut file if applicable)
* `support.py`
  * any functions that we define but do not preload
  * barely ever used -- I'm considering removing it
* `analysis.py`
  * the static analysis (see below)
* `tests.py`
  * the unit tests (see below)

**Static Analysis**

The static analysis file must define one variable, `ANALYSER`, which contains an instance of a `CodeAnalyser` subclass (see example).

It should define two classes:

* a `TutorialNodeVisitor` subclass
  * this visits each 'node' in the AST
  * the definition of node types is [available here](https://docs.python.org/3/library/ast.html#abstract-grammar)
  * to visit a node of a given type, define `visit_NodeType` (eg `visit_FunctionDef`)
    * you *must* call `super`
    * you can assume that visits occur top down, depth first
  * `TutorialNodeVisitor` defines helper methods, eg to get the identifier (variable, method, or function name) of a node
    * check out `tutorlib.analysis.visitor` for definitions, which are mostly imported from `tutorlib.analysis.ast_tools`
    * you can call these as, eg, `TutorialNodeVisitor.identifier(node)` (not `self.identifier(node)`, as it's a class method)
  * `TutorialNodeVisitor` will automatically do a bunch of analysis, which you don't have to repeat:
    * it records all function definitions (in `self.functions`)
    * it records all class definitions (in `self.classes`)
    * it records all function calls (in `self.calls`)
    * see the comments for the types of these, and the existing packages for usage
  * it is very important that nothing in this class raises exceptions
* a `CodeAnalyser` subclass
  * this must define an `_analyse()` method
  * `self.visitor` contains the `TutorialNodeVisitor` subclass you defined
  * `self.add_error` adds an error (only the first error will be shown to the user)
  * `self.add_warning` adds a warning (all warnings will be shown by default)
  * this method *must not* raise exceptions

As for working out what visit methods to use and what to do with them, that's basically up to you.
You can base things off the old code if you want, but I tend to rewrite things from scratch (just looking at the old error messages to see what I need to catch), as the API has changed a fair bit.

The [abstract grammar definitions](https://docs.python.org/3/library/ast.html#abstract-grammar) tell you what the types of possible nodes they are, and what attributes they may have (the things in brackets, basically).

To double check things, I tend to use pdb in ipython to print out info on a node, and test everything works.  I usually define something like this at the shell, and then play with `node`:

````
class CV(TutorialNodeVisitor):
    def visit_FunctionDef(self, node):
        import pdb; pdb.set_trace()
````

**Unit Tests**

The variable `TEST_CLASSES` must be defined to be a list of `StudentTestCase` subclasses (not instances).
These will be shown to the student and run in the order given, so they should go from simplest to most complex, with edge cases (probably) at the end.

Notes on `StudentTestCase` subclasses:

* these are `unittest.TestCase` subclasses, so any test method is available (`self.assertEqual`, `self.assertIsNone` etc)
* each subclass must define two class variables:
  * `DESCRIPTION`
    * a description of the test, shown to the user
    * I normally make this a string with expected inputs and outputs, eg `DESCRIPTION = 'add(2, 3) -> 5'`
    * because students see this, it's part of the documentation for the question, so it's appropriate to include edge cases (eg, what happens if the input is an empty sequence)
  * `MAIN_TEST`
    * the name of the main test method (as a string)
    * this is a bit redundant, and I might nuke it later, but for now it's required
* each subclass must contain *at least* one test method (the one in `MAIN_TEST`)
  * this is thee method the student will be shown the output from
  * this should do exactly what `DESCRIPTION` says
* each subclass may (and should) contain at least one other method
  * this should test something similar to the `MAIN_TEST` (so, eg, in the above example, it could try to add two *different* positive integers)
  * this exists purely to prevent students special-casing all the tests (by returning what the `DESCRIPTION` tells them to)
  * students will never be shown the output of this method (just told that something is wrong if it fails); this is why it's so important that it tests the same functionality as the main test method
* each subclass should test exactly one thing
  * so, eg, one subclass might test adding zero to a positive integer, another might test adding two positive integers etc
* you can have as many subclasses (and thus different tests, visible to the user) as you want, but try not to go overboard

**Comment by pjritee** [comment]
I note that urllib2 has been merged into urllib and I also note that the 
read now returns a bytes object and now needs a decode('utf-8') to 
translate to a string. I assume that in tutorial 8, the parser now works 
on bytes objects. Is that correct?

**Comment by pjritee** [comment]
If you want me to process your claim forms before Easter you will need 
to submit them before 10:00 this morning. I will be disappearing after 
the lecture.

**Comment by pjritee** [comment]
I have updated assign1_sample_tests.py in the repository to ignore 
trailing spaces - lots of students are struggling with that and it's not 
obvious from the assignment sheet what the spacing is.

Ben - can you update the test file on the web page (and add a comment 
that it's been changed) and then post something to piazza about the 
change and why.

Michael - this probably changes your tester for the assignment - can you 
modify so that trailing spaces are ignored.
