### ISSUE TITLE
Unable to delete password from keychain error

### ISSUE THREAD

**Issue by RoryCharlton** [CSSE1001/MyPyTutor#152]
A few students have mentioned that they have experienced an error when running mpt (on OS X Yosemite) that tells them that they are unable to delete a password from the keychain, despite not having messed with the keychain at all.
Is there a simple work-around that I'm missing or is this more likely to be something wrong with the student's setup?

**Comment by sapi** [comment]
Looks like there's actually an exception when you try to delete a
non-existent password.  I guess that can happen under certain
circumstances, if  WebAPIError is thrown at the wrong time.

I'll push a (hopeful) fix.
