### ISSUE TITLE
problem with admin page

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#153]
There are a couple of students that have done 100% according to the top-level page but when I look in detail it says they have not submitted some problems - e.g. the "Using Functions" problem. I looked at my entry and it also says I haven't done that problem even though I have.

**Comment by sapi** [comment]
There should be a warning at the top of each progress page explaining this.  See #116 for more details.

The short version is that `get_submissions` in `progress.py` isn't using the correct logic to determine the user's submissions; it's unaware of updates to tutorials.  The summary (from `admin.py`) does call the correct support functions, and so does return the correct result.

I'll try to sort this out today.

**Comment by pjritee** [comment]
I thought as much

**Comment by jgat** [comment]
@sapi: Is this currently being worked on? I could look at it for the next half-hour or so.

**Comment by sapi** [comment]
I'm applying a fix as we speak, all good :)

**Comment by sapi** [comment]
@jgat Was there a reason for changing to `.get` in `get_submissions_for_user` in 2eccd737 ?

The comment and the code currently disagree there, and I want to make sure that I change the correct one.

(My understanding behind the comment/original code was that a lookup could never fail in the absence of a server error.  I was intentionally throwing an exception in those cases.)

**Comment by pjritee** [comment]
Seems to be working for me

**Comment by jgat** [comment]
Note: now that this issue is fixed, you could link students to http://csse1001.uqcloud.net/cgi-bin/mpt3/progress.py if they want to see details of their submissions, with the admin features removed. (e.g. add a link to the course website, or replace the existing "show submissions" menu item in the app.)

**Comment by sapi** [comment]
I think it would be a good idea to add the link to the site.

I'm in two minds about whether to replace it in the app, though.  We need to get submissions in the app anyway (to color the menu items), so it's not really anything extra to have in the code.  Annoyingly, it looks like there's no way to pass the auth cookie to `webbrowser`, meaning that the user would need to log in again to view submissions using the web link.

**Comment by pjritee** [comment]
I agree - the Show Submissions in MPT is working OK so I'd leave it - I guess, given the student has to log on again then it's not clear that many students would be bothered to use the web version.

**Comment by sapi** [comment]
I think a link on [this page](http://csse1001.uqcloud.net/mpt-problems.html) would be handy.

@athleticus Thoughts?

**Comment by jgat** [comment]
And/or a link on the blackboard page where they view their marks for assignments/exam (if possible).

**Comment by pjritee** [comment]
If they were already logged in to Blackboard I guess they would still have to enter username and password again

**Comment by jgat** [comment]
Yes they would, but if a student was on the blackboard site, they probably
want to know their marks for all their assessment pieces. So putting a link
there would still be helpful, even if they have to enter their credentials
once more.
