### ISSUE TITLE
Error in tests text for Processing Lists Using a for loop

### ISSUE THREAD

**Issue by starsnabove** [CSSE1001/MyPyTutor#154]
The answers in the bottom left of the MyPyTutor's problem  "Processing Lists Using a For Loop" states that the input "has_gt([1, 2, 3], 5) -> True"   whereas the code needs to return as False to adhere to the given requirements and to be counted as correct to submit.

**Comment by pjritee** [comment]
That appears to be a problem in the description of the test - not the test itself

**Comment by sapi** [comment]
Thanks.  That (and one other typo in that problem) should be fixed now :)
