### ISSUE TITLE
If statement 1 problem

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#156]
I think we need to add something like "use a single if statement and a single print statement".
I student on piazza is saying that their working code is not being accepted (and it's for this reason).
The static analysis says this but it should also be stated in the question

**Comment by sapi** [comment]
We mention that this happens on the [help page](http://csse1001.uqcloud.net/mpt3/help/):

>  The 'Analysis' section provides tips and hints to help you complete the problem. Once your code is correct, you shouldn't see anything here. We require you to complete some problems in a specific way (for example, by using a for loop. If so, this requirement will be shown in the 'Analysis' section.

I think directing students there is preferable to repeating ourselves in every question.

**Comment by pjritee** [comment]
Good point - I forgot about that - maybe that's better - I'll close
