### ISSUE TITLE
extracting MPT results from server

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#164]
It's nearly that time of semester when I need to be able to extract the marks - how do I do that?

**Comment by jgat** [comment]
I might implement that soon... (the first barrier is figuring out the best way to ssh into the web zone for development purposes from outside the university network - probably either checking if I can get a VPN working with my staff account, or requesting access to moss/lichen through ITIG and then ssh'ing to the zone via one of those).

It's probably written down somewhere else, but what format would you like to download them in? If CSV, how would you like the rows to look? (e.g. "student_number,total_mark" or something else? Total mark as a count of the number of correct questions, or scaled to be out of 10?)

**Comment by pjritee** [comment]
My current script for merging the MPT marks into the class marks file is to read in a file whose lines are
like
s1234567, 9.3
i.e. an 's' student number then comma then float mark out of 10

**Comment by sapi** [comment]
code/get_submissions.py should do this (or something similar) already,
although it doesn't make use of the web interface (it's a CLI script).

I wrote that a while ago, though, so it's missing some of the newer
features (like late submissions and class lists). Up to you whether it's
worth updating that or just starting anew with a web-based solution.

**Comment by jgat** [comment]
The admin site now supports a CSV export:

* Go to http://csse1001.uqcloud.net/cgi-bin/mpt3/admin.py
* Use the checkboxes to select students who you wish to export marks for (or use the top checkbox to select all students in the current filters).
* Under "Action", select "Export marks to CSV"

The CSV output is as described above, with a float mark out of 10.

Note that the default view for the admin interface is now "Show only enrolled users". You may wish to swap to "Show all users", but this will include people who are not students in the course (e.g. tutors, myself, uqprobin).
