### ISSUE TITLE
Finding Digits in String

### ISSUE THREAD

**Issue by athleticus** [CSSE1001/MyPyTutor#171]
Testing correct solution for Finding Digits in String problem causes an error in static analysis on Python 3.5 on OS X, but does not occur in 3.4. Unknown if issue exists on Windows/Unix also.

**Comment by pjritee** [comment]
Are you reasonably confident this is the only problem suffering from this bug?

**Comment by athleticus** [comment]
No. Not until the cause is determined. I think this may be related to the original error that arose when we upgraded to 3.5, which was to do with arguments somehow.

**Comment by r-portas** [comment]
The same issue happened on a lab machine running Python 3.5

**Comment by TRManderson** [comment]
Successfully replicated on Ubuntu too. Attempting to diagnose the issue.

**Comment by TRManderson** [comment]
Python 3.5 removed "starargs" from the abstract grammar of function calls in 3.5. Becase PEP0448 is included in python 3.5, the ability to have multiple unpackings (ie `fn(*args1, *args2)`) had to break backwards compatibility. Doing a workaround.

**Comment by TRManderson** [comment]
The fix in #173 means that nothing that would otherwise be okay is currently broken, but there might be more implications in how we interact with the AST. I'll see if I can find any more, but that solves this issue.

**Comment by TRManderson** [comment]
Doing a diff on the abstract grammar, it seems that this is the only change that breaks backwards compatibility. All the other changes are adding the new async features.
