### ISSUE TITLE
EditorWindow -> Check Menu Not Working

### ISSUE THREAD

**Issue by applebyter** [CSSE1001/MyPyTutor#176]
In the editor window the Check menu is not causing the check to happen. F5 works correctly in getting the program checked. Has the event handler been miss-wired at some point with the menu item?

**Comment by justinl1996** [comment]
This should be fixed in the latest pull request

**Comment by uqposhe1** [comment]
Hi Richard,

Can you take me off the mailing list for this semester in CSSE1001. It will be a little distracting getting all the emails,

Thanks,

Peter
