### ISSUE TITLE
MPT configuration file behaviour on initial load and when tutorial directory unavailable

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#29]
Needs to look in home folder for config file (mypytutor.cfg)

**Comment by sapi** [comment]
When the tutorial directory is unavailable (incorrect), parsing the tutorial package fails and an error is displayed.

I'm happy enough with this behaviour; I don't see the benefit of complicating things with additional logic here.

Closing this issue, on the understanding that #64 will add validation to tutorial file entries.
