### ISSUE TITLE
OS X Compatibility

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#49]
There seem to be some issues with OS X compatibility.

I'm experiencing issues on 10.10.2, with Python 3.4.1.  (Haven't checked what the underlying tk/tcl version is as yet.)

Most annoyingly, dialog boxes appear to be impossible to dismiss.

10.10.2 is current a beta, so it's possible that the current version isn't compatible with tk/tcl.  I also haven't tried updating tk/tcl as yet, but will as the next step of troubleshooting.

We really need to work out what is going on here, especially as the dialogs are purely under tk's control (we don't have *any* code running which could cause the problems to be our fault).

**Comment by sapi** [comment]
This is still a problem with ActiveState TCL 8.6

Sadly, the MWE is pretty simple:

````
In [1]: import tkinter.messagebox

In [2]: tkinter.messagebox.showinfo('Uhoh', 'This is going to stay on screen')
Out[2]: 'ok'
````

We might have to implement our own messagebox (not hard, but will look out of place on some operating systems).

**Comment by sapi** [comment]
The window disappears if a root window is created first:

````
In [1]: import tkinter as tk

In [2]: import tkinter.messagebox

In [3]: root = tk.Tk()

In [4]: tkinter.messagebox.showinfo('Hi', 'info')
Out[4]: 'ok'

# window disappears
````

But that is what should be happening in the main loop for the normal app.  It could be that Cocoa isn't telling the main window to enter the main loop again?  Hmm...

**Comment by sapi** [comment]
@dartmoth indicated that this is still an issue on a virgin install of Python 3 on OS X, so I'm reopening.

We should check with the updated version of tcl/tk; students need to get this anyway to use IDLE successfully.

If we *can't* fix this with the force-refresh workaround I added in 8b749f2, then the easy solution is to just implement a DIY messagebox (probably a simple subclass of `Dialog`), do a runtime check for OS X in `messages.py`, and serve that up instead.

**Comment by jgat** [comment]
Can confirm that this is an issue on OS X 10.10. Steps taken:

1. built and run from a fresh clone, with no `~/.mptrc` file.
2. selected a tutorial and answers directory
3. got a prompt to log in, cancelled
4. got an error message ("Please check your credentials and try again..."), that error message wouldn't close. (not exactly the best error message, that's a tangential issue)

Once I exited the application and reopened it (now with a `~/.mptrc`), I again cancelled the login prompt, and the error message would close. Repeatedly opening and cancelling the login dialog would repeat the error message and it would be closable.

Possible cause: the configuration dialog messes up something (e.g. if it gets created before mainloop is invoked, it might spawn its own Tk instance, which causes later messagebox dialogs to fail?)

**Comment by sapi** [comment]
Interesting.  I can reproduce that as well.

It doesn't look like the dialog uses its own Tk instance; it's given a reference to the existing root window.

Perhaps there's some issue with the dialog being called from the initialiser of the app?  I can't imagine why though -- the app isn't a Tk subclass, so even if some weird timing issue were possible, I wouldn't have thought we'd see it there.

It looks like it's something to do with creating the popup from within the initialiser, though.  Deferring it hides the issue (see commit).

The whole tutorial selection thing is really clunky atm, anyway.  I'm not going to merge the hotfix into master until that's been cleaned up.
