### ISSUE TITLE
Set correct file/directory creation modes for student files on server

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#54]
The default creation modes for directories are needlessly permissive.  (Files may be the same, but from memory they're ok.)

We need to double check what the correct permissions are, based on how the server accounts are set up, and then set them in `support.py`.  The locations to change are marked with TODO notes.

The correct mode is probably `rw-r-----`.

**Comment by jgat** [comment]
Directories generally require +x, so maybe `rwxr-x---`.

**Comment by sapi** [comment]
Given our use of `mypy`, this is no longer really applicable.
