### ISSUE TITLE
Closing editor window should close MPT

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#67]
Closing the editor window should close MPT.

Alternatively, closing the editor window should be disabled (I don't like this approach).

Alternatively, MPT should be smart enough to re-open the editor window if it's closed and a new tutorial is loaded.  (I don't like this, as there's a bit of internal state that assumes the editor exists if the current tutorial does.)

**Comment by hendo-michael** [comment]
I think the student should be able to close the editor window without closing MPT (I thought this was a bug the first time I did this). Otherwise, the editor window should be open when opening MPT and closing of the editor window should be disabled.

**Comment by sapi** [comment]
I can't seem to reliably reproduce this issue at the moment; whenever I try to close the editor window, MPT *does* close.

If someone else can reproduce it, please reopen this issue.

**Comment by pjritee** [comment]
MPT closes for me when I close the editor window
