### ISSUE TITLE
Problem 1 of MPT (Introduction)

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#73]
This has been redone but it still needs more work. It is still (mostly) describing the old layout. It would also be useful to explain that the tests will be run before the user has run any code and that will typically mean lots of red (failures) but that will change as the user enters code.

**Comment by sapi** [comment]
I think it would also be good to add screenshots here.  There's already support for doing that thanks to the GUI questions.

Screenshots should be taken on windows, as it's the most common operating system.  No point taking them on OS X, as it's too fugly!

**Comment by jgat** [comment]
Ideally, take screenshots from the EAIT lab environment

**Comment by sapi** [comment]
@starsnabove Do you mind doing this as part of your MPT video?  It'd be good if the static images matched the ones in the video.
