### ISSUE TITLE
help menu

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#76]
I get
  File "/home/pjr/research/MyPyTutor3/MyPyTutor/code/tutorlib/gui/dialogs/help.py", line 93, in __init__
    TextDialog.__init__(self, parent, title, HELP_TEXT, bg="#ffffaa")
TypeError: __init__() got an unexpected keyword argument 'bg'

Maybe we make the help start up the browser and we can put more details about layout, screenshots etc in that page as well as details about what students should expect to see

**Comment by sapi** [comment]
Ah damn, I must have forgotten to transition that dialog to `ttk` properly (`ttk` widgets use styles instead of backgrounds).

I actually really like the idea of shifting the help to the browser.  That also has the advantage of us being able to update the help text (in response to student questions) without needing to push an update to MPT itself.

**Comment by pjritee** [comment]
What might be useful (especially in relation to #80 ) is to put in a list of the error messages produced by MPT with an explanation of what they mean. This would mean the MPT errors could be close
to error messages produced by the interpreter and so it would probably help students understand both the problem in MPT and in their assignment code.

**Comment by pjritee** [comment]
Anyone want to put their hand up to write a HTML version of help with some screen shots, noting that the tests will be run even before the user enters code (and maybe the philosophy behind it), and some discussion of the errors produced by MPT

**Comment by hendo-michael** [comment]
I can do that this afternoon.

Kind Regards,

Michael Henderson

-------- Original message --------

**Comment by pjritee** [comment]
Thanks - of course things might change a bit as the code gets upgraded/extended/fixed but as Sean says it's a bit easier to maintain because it's separated from the code.

Also the About menu item is just about me - needs updating to be consistent with copyright info

**Comment by starsnabove** [comment]
I can put together a html help.

**Comment by pjritee** [comment]
Any progress on this issue?

**Comment by hendo-michael** [comment]
The help menu is done I just have to upload it to github which I will do tonight.

-------- Original message --------

**Comment by pjritee** [comment]
Great - there will almost certainly be some minor changes as the MPT code gets polished up.

**Comment by sapi** [comment]
What URL will we host it at?  It's easy enough to integrate it into MPT.

**Comment by pjritee** [comment]
I think putting it in with MPT makes sense as the help is really part of MPT and not the course web pages directly. I think Ben was suggesting this.

It might be worth adding something like
"If you are new to MyPyTutor please use the help menu to look at the documentation"
(or something like that) to the start screen

**Comment by sapi** [comment]
@hendo-michael Can you please push this to the repo?

I cleaned up `doc/` just before, so my preference would be to create a `static/` directory in the root of github and store it there.  We could then change the build scripts to put the zipfiles in there as well.

**Comment by hendo-michael** [comment]
I created the static/ directory and placed the files in there. Have a look at the site and let me know what you think.

**Comment by sapi** [comment]
Thanks @hendo-michael 

I cleaned it up a bit (mostly deleting stuff on old features), but otherwise didn't change very much.

It's probably worth having someone have another look at this / update it after we've had students work with the app for a little while, so that we know the common errors.

**Comment by pjritee** [comment]
Looks good - my only thought is that its probably worth saying that the tests will be run as soon as you change to a new problem (even if you have not written any code). It might cause students to freak out if we haven't warned them. We might consider adding a few words about why we are doing this (i.e. using a test driven approach)

**Comment by sapi** [comment]
@hendo-michael What's the purpose of the `font-awesome` stylesheet?  Is it actually being used?

**Comment by jgat** [comment]
Probably not a bad idea also to get rid of the bootstrap and jquery CSS/JS files from this repo, and edit the links in the html to point to some other location either on the course website, or on the external web (look at the source for the csse1001 homepage for example).

**Comment by athleticus** [comment]
> Probably not a bad idea also to get rid of the bootstrap and jquery CSS/JS files from this repo, and edit the links in the html to point to some other location either on the course website, or on the external web (look at the source for the csse1001 homepage for example).

This is a good idea, except that it then makes MPT strictly dependent upon the website (which may change). There is nothing wrong with using a package manager, like [Bower](http://bower.io/), to manage front-end dependencies (CSS/JS) - in fact, I'd recommend that route.

Another solution is to use a cdn. I.e. (remove the .min to get unminified).

jQuery
https://code.jquery.com/jquery-1.11.2.min.js

Bootstrap
[//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css](//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css)
[//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js](//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js)

Font-Awesome
[//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css](//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css)
