### ISSUE TITLE
Classes and Objects group

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#81]
There appears to be a major copy-paste error. Problems have been repeated.

**Comment by sapi** [comment]
Could you please provide a screenshot of what you mean?  It looks the same as usual on my end.

**Comment by pjritee** [comment]
Oops - my bad - it is the Classes, Error handling, I/O group - at least the first 2 problems seem to be the same.

**Comment by dartmoth** [comment]
I think that was a problem I did, I'll have a look at it.

**Comment by pjritee** [comment]
Fixed
