### ISSUE TITLE
problem with code analysis?

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#82]
For the Using Classes problem I wrote

    if friend is not None:
        print("Friends with {}".format(friend))

and got (in the terminal - god knows what happens if run in windows)

  File "/home/pjr/MyPyTutor3/MyPyTutor/code/tutorlib/analysis/ast_tools.py", line 87, in identifier
    'No known identifier exists for node {}'.format(node)
tutorlib.analysis.support.StaticAnalysisError: No known identifier exists for node <_ast.Str object at 0x7ff2d5f10a90>

**Comment by sapi** [comment]
That's an error in the static analysis code; there must be an edge case I forgot about. 

Using Classes was one of the first problems I wrote using the new framework, so I wouldn't be surprised to find that I just made a silly mistake. 

I'll take a look once I have access to a computer with internet; thanks.

**Comment by sapi** [comment]
This has since been fixed.
