### ISSUE TITLE
Colours in problem menu(s)

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#85]
In the old version the individual problems would get highlighted in blue if submitted on time and red if submitted late (and black if not submitted) and at the top level highlighted if all problems in that section submitted on time and red if at least one problem submitted late. I think students found that quite useful.

**Comment by pjritee** [comment]
When I first login I don't see the menu items of problems done as blue but after "Show Submissions" it's OK (and is updated when I submit a new problem)

**Comment by sapi** [comment]
Are you logging in using the initial popup, or later?

It just occurred to me that I need to make sure that there's a post-login hook which attempts synchronisation of problems and downloading of the solution status no matter how the student logs on. 

I'll probably slightly modify the callback system in SessionManager to achieve that.

**Comment by pjritee** [comment]
Yes - it's logging in using the initial popup - I haven't tried a latter login yet

**Comment by pjritee** [comment]
I can confirm that the the sub-menus are highlighted blue when done. I can't confirm that the top-level
menu is highlighted because the while-break is listed as Unknown (as are a few more). I guess it's an inconsistency with the server hashes. Not sure how we can test for late submissions - I guess we could temporary set the intro set to last week.

**Comment by sapi** [comment]
I'm not trying to highlight the top-level menu at the moment.  It was a bit
fiddly, so I deferred it till later.

You could just edit the submission time on the server to test late
submissions.
