### ISSUE TITLE
More problems fo inheritance week

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#86]
There is only one problem so far - the other problem (from the old system) won't really work as is but I am struggling to think of a replacement (or other questions). Any bright ideas?

**Comment by sapi** [comment]
I think @dartmoth was redoing that one using print statements instead of assignments. 

I'd like a question on abstract methods (ie, override to implement one or more methods which are called from a pre-written implementation in the base class).

**Comment by jgat** [comment]
I do like that question, so something similar would be nice - basically something testing the student's understanding of the method resolution order. (It's also a nice bonus that it's similar to an exam question)

**Comment by pjritee** [comment]
Agreed but the 'old' problem had the test hidden but in the new MPT the results of the tests are there for all to see so if the question was like the old one (or more consistent with the new approach) "print the call list" then in the test window we would have
something -> 'call1, call2, call3'
and so it becomes a non-question - unless there is a way of writing the problem I don't understand.

**Comment by sapi** [comment]
The test description can always be something like 'Correctly prints the resolution order for C1'

**Comment by sapi** [comment]
I'd like to ask a question on polymorphism, but I'm struggling to come up with anything which is both interesting and simple enough for MPT.

Ideally, I'd like to have some prewritten code which does the interesting stuff, eg:

    class Shape():
        def draw(self):
            pass

    class Canvas():
        def draw(self):
            for shape in self.shapes:  # students provide shape instances
                shape.draw()

@jgat @pjritee Any ideas on something in this vein which would be simple enough for a MPT question (and which isn't html parsing)?

**Comment by pjritee** [comment]
Is it worth having origin in Shape and Square if it's not used in any example?
What does total_area really mean if everything is at origin as shapes will overlap (can't really deal with this even if not all shapes are at origin).

**Comment by sapi** [comment]
I was thinking of just including it as an example of keyword arguments.  I
might add in a rectangle test which requires it?

It probably isn't that meaningful, but it's a contrived example.

**Comment by pjritee** [comment]
It would be better to add an example using a shifted rectangle and maybe for your square example one could have a shifted origin
