### ISSUE TITLE
Progress webpage

### ISSUE THREAD

**Issue by jgat** [CSSE1001/MyPyTutor#87]
Low priority, but it might be fun:

Create a CGI-based webpage on the course website that tells students which MyPyTutor problems they've completed (and any other interesting data we have, such as when they submitted it). This webpage can then be linked to either from within the application or from the course website (or both).

Since all this info is already on the course server anyway, it would just be a matter of retrieving it and throwing some simple HTML/CSS around it, and having a small python handler to pull it all together.

**Comment by sapi** [comment]
I like the idea. I think I may actually be returning JSON for the appropriate call, which would make this very straightforward.

**Comment by pjritee** [comment]
In #85 I mentioned putting colours on the problem menu to show progress - there is also a menu item to show submissions. Are you thinking of this as a replacement or an alternative? I'm easy - but I think adding colours to the problems menu gives students quick feedback

**Comment by jgat** [comment]
The progress page is in a usable condition, I'll consider this complete; any further major requirements can be raised as a separate issue.
