### ISSUE TITLE
Nicer behaviour when there's no internet connection

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#93]
WebAPI should try detecting an internet connection, perhaps by querying a website with a short timeout.

This is particularly irritating with the bootstrap process.

**Comment by jgat** [comment]
"Nicer behaviour" is probably the wrong phrase in the title of this issue, at least from a user's perspective - having an application refuse to start up is not nice behaviour.

**Comment by sapi** [comment]
Oh, I completely agree with you.

I'm on the fence about whether or not that 'fix' was a good idea.  (Didn't intend to close this; github got a bit overzealous on the keyword matching.)

I think, given that the internet could drop out at *any* time, we need to put in proper error handling and then revert 2909ec8

**Comment by sapi** [comment]
Should be mostly handled now.  Please reopen if you see anything silly.

Atm, the only irritant that I'm aware of is that you'll get two popups if you start the app while offline.  Serves you right, though :P
