### ISSUE TITLE
Make MPT repo public again

### ISSUE THREAD

**Issue by sapi** [CSSE1001/MyPyTutor#95]
@athleticus @pjritee 

The repo seems to have become private over the last week or so for some reason.

I don't see any reason to keep it this way.  Students can read the source code off their own computers; there's no reason to hide it from the internet.  This includes the problem sets; we decided not to keep them secret.

I'd like committed students to be able to raise issues against the repo, and possibly even make contributions.

**Comment by athleticus** [comment]
Sounds like a consensus to me.
