### ISSUE TITLE
problem with logon 

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#96]
This may be related to other issues but I just started up MPT and put in my user name and password and it responded with "Incorrect username password" and I pressed cancel and it logged my on

**Comment by pjritee** [comment]
This problem is critical - it's holding up my testing. It's very strange - it displays that I am logged on but it doesn't seem to be doing the right thing. I can't tell if I am really logged on - the login window tells me there is an error but when I press cancel the status line says I am logged on but when I submit and then look at submissions it doesn't show the changes

**Comment by sapi** [comment]
I think fixing the `AuthError` issue in af27d81b47f049119cc5af7a4f94d86cec153769 has also fixed this.

Previously, I couldn't log in using my staff account (although the student account worked fine).  Now, I can log in with both without issues.

Let me know if it doesn't work for you.

**Comment by pjritee** [comment]
I get an incorrect user name or password error - when you say you can log in without issues do you get this "error". We can't have this error showing up to students - that would be a disaster.

**Comment by sapi** [comment]
I don't get any errors at all when I log in. Could you provide the exact
text of the error you're seeing please?

**Comment by pjritee** [comment]
![login](https://cloud.githubusercontent.com/assets/4810594/6238978/1225ea7c-b74b-11e4-8b97-05cc0fe58aca.png)

**Comment by sapi** [comment]
I can't seem to reproduce this, unfortunately.  Both my student and staff accounts authenticate without issue.

I assume you have no issues with UQ SSO for other sites/apps?

@jgat Does your staff account work for MPT?

**Comment by pjritee** [comment]
Curiously it's now working for me but I did a pull that had updates to web_api and sessions so that might have fixed the problem (I did a pull earlier in the day that didn't have those updates).  When I do a show submissions there are lots of Unknowns - does some files needs to be reset on the server so this will work again?

**Comment by sapi** [comment]
Yeah, the hashes need to be put back in sync.

Make a backup of the two local files (just in case), then try this:
* download tutorial_hashes and tutorial_hash_mappings from the server, and
overwrite the local files
* make
* upload the resulting tutorial_hashes and tutorial_hash_mappings files to
the server

I don't have Internet to verify, unfortunately, but that should
theoretically work.

**Comment by pjritee** [comment]
Why do I need to download the server hashes - doesn't make build new hashes?

**Comment by sapi** [comment]
It does, but the sever doesn't know about all of the intermediate stages we
went through during development. The diffs/mappings only need to be between
versions of the tutorials that the server has seen.

**Comment by pjritee** [comment]
That seemed to work - no more Unknowns (and I can login without problem)

**Comment by sapi** [comment]
Excellent. Feel free to reopen this if you get any further login issues.
