### ISSUE TITLE
uploading feedback broken

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#97]
this needs fixing - I am sure we will have lots of feedback this semester

**Comment by sapi** [comment]
@pjritee Should feedback be anonymous?

**Comment by pjritee** [comment]
problem feedback should be anon because the code is sent along with the student feedback.
For MPT feedback it's really about MPT itself and so could be open.
I guess there is an argument (which I have just been thinking about) that this could be better done through Piazza - the problem with the old style feedback is that I tended to not look at it very much until after the semester.
Thoughts???

**Comment by sapi** [comment]
What is the significance of including code as far as problem feedback needing to be anonymous?

I feel like students might be a bit less keen to submit feedback in Piazza, as they'll probably view it as more 'public'.  It'll also be harder for us to access.  We could set up a daemon to email us on new feedback?

**Comment by pjritee** [comment]
Ah - confusion of anonymous - I didn't mean anonymous in terms of the person - I should have been saying 'private' - i.e. other students can't see the posts of other students.

**Comment by sapi** [comment]
Ah got it.  I intend to keep everything private, but I think it would be useful for us to know who submitted what feedback.

**Comment by pjritee** [comment]
Yes - in fact I suggested students put in their email if they wanted a response
