### ISSUE TITLE
feedback when problem submitted

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#99]
It would be good if there was some quick feedback when a student, who was logged on, did a successful check and the answer was automatically submitted. Maybe something like "Correct and Submitted" (perhaps in blue) in the status bar????
On the other hand, in the using functions problem for example, where the student was supposed to use double and increment instead of * and + - if the student used * and + then the test window says Correct but the analysis window says there is a problem. A student might think that because they got Correct then the answer would be submitted. In this case there needs to be some sort of negative feedback.
Maybe instead of saying "Correct" it should say "Test Passed". Maybe a negative status message (in red) in status bar????

**Comment by sapi** [comment]
Sounds quite close to what we were thinking in #91.  I'm going to merge the discussion in there.

I like the idea of something in the status bar, which could then distinguish between failures in testing, analysis, and the problem being fully submitted.
